### ISSUE TITLE
Does Trivy Dream?

### ISSUE THREAD

**Issue by joe-kimmel-vmw** [carvel-dev/secretgen-controller#101]
**What steps did you take:**
I didn't do it, actually. I was nowhere near there when it happened. It didn't even happen in a place! Several people saw me walking around outside near my residence and they're all willing to testify.  I'm innocent, I swear!

**What happened:**
https://github.com/vmware-tanzu/carvel-secretgen-controller/runs/7909711621?check_suite_focus=true

**What did you expect:**
Trivy not to fail

**Anything else you would like to add:**
Is the issue that Neil recently fixed all the vulnerabilities, so now we're learning that there's a bug in the codepath that happens if there was nothing to report?

**Environment:**
github action runner

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joaopapereira** [comment]
Take a look at this commit https://github.com/vmware-tanzu/carvel-release-scripts/commit/88586bd17419ef65b0aecbcf354f3cfd13b60fac it should provide the solution for this issue
