### ISSUE TITLE
Promote this project out of experimental

### ISSUE THREAD

**Issue by aaronshurley** [carvel-dev/secretgen-controller#14]
**Describe the problem/challenge you have**
As secretgen-controller is maturing and being promoted out of experimental, we should ensure that the repo is in a good state so that users can build trust with the tool.

**Desribe the solution you'd like**
- [ ] ~~promote secretgen-controller out of the "experimental" section on [the website](https://carvel.dev/)~~ _skip this for now as we re-think our homepage layout_
- [x] promote sgc on [carvel repo](https://github.com/vmware-tanzu/carvel/blob/develop/README.md) ([GOVERNANCE](https://github.com/vmware-tanzu/carvel/blob/develop/GOVERNANCE.md)). The secretgen-controller tile will point to the GitHub URL.
- [x] ensure that secretgen-controller repo is in good shape
  - [x] simple and focused README
  - [x] clear "getting started" guide for users and contributors
  - [x] design & architecture docs, if applicable
  - [x] MAINTAINERS & GOVERNANCE files
  - [x] SECURITY.md file
  - [x] issue templates
  - [x] github actions (for PRs, label mgmt)
  - [x] dependabot
  - [x] good first issues are labeled

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Comment by aaronshurley** [comment]
Merge this with #9

**Comment by joe-kimmel-vmw** [comment]
marking dependabot as 'done' bc the settings / security-and-analysis page looks the same as kapp-controller.

**Comment by joe-kimmel-vmw** [comment]
I don't see `MAINTAINERS & GOVERNANCE files`. in kapp controller or imgpkg

**Comment by aaronshurley** [comment]
@joe-kimmel-vmw yeah... We wrote this list before all of these things were rolled out across the tools. We _just_ published an updated [GOVERNANCE.md](https://github.com/vmware-tanzu/carvel/blob/develop/GOVERNANCE.md) and [MAINTAINERS.md](https://github.com/vmware-tanzu/carvel/blob/develop/MAINTAINERS.md) in the `carvel` repo. Our idea is that each tool's GOVERNANCE/MAINTAINERS doc will just point back to the `carvel` repo's instance.

**Comment by aaronshurley** [comment]
Closing this issue out. We decided to hold off on any website homepage changes for the moment as we're considering making some bigger website refactors.
