### ISSUE TITLE
Option to make secret accessible to all namespaces

### ISSUE THREAD

**Issue by abenabid** [carvel-dev/secretgen-controller#25]
**Describe the problem/challenge you have**
Sometimes isn't possible to predict what namespaces need to access a shared secret.

**Describe the solution you'd like**
It would be nice to have the possibility to share the secret to any namespace via a flag.

**Anything else you would like to add:**
N/A

Thank you

**Comment by cppforlife** [comment]
this just became possible in v0.5.0. you can use `*` as a namespace name in SecretExport. docs coming (hopefully today).

**Comment by abenabid** [comment]
Hello,

Good news, I'm using the latest version and it works !

Best regards

**Comment by cppforlife** [comment]
documented within https://github.com/vmware-tanzu/carvel-secretgen-controller/blob/develop/docs/secret-export.md
