### ISSUE TITLE
Support KMS provider

### ISSUE THREAD

**Issue by StarpTech** [carvel-dev/secretgen-controller#3]
Perhaps rely on https://github.com/mozilla/sops directly. The same as in https://github.com/k14s/kapp-controller/blob/3afee6986bac4a26b60d86c6131504d3404265be/pkg/template/sops.go

Btw: I really like the concept. It makes complete sense to implement this as a controller. In that way, the procedure to generate the secret is stored in git but you can't run into the situation where you accidentally commit your password. You will never touch the secret.

**Comment by cppforlife** [comment]
@StarpTech could you elaborate a bit more what you are proposing and where does sops fit in?

**Comment by StarpTech** [comment]
Nevermind, it's possible to enable https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/ cluster-wide.
