### ISSUE TITLE
Bump go version to latest

### ISSUE THREAD

**Issue by aaronshurley** [carvel-dev/secretgen-controller#32]
**Describe the problem/challenge you have**
We want to ensure that the code remains compatible with the latest versions so that we do not risk falling behind and on an unsupported version (note: go supports n-1 versions).

**Describe the solution you'd like**
The code runs on the latest version of go.

**Anything else you would like to add:**

**Comment by joe-kimmel-vmw** [comment]
we did this at some point and just failed to tag it
