### ISSUE TITLE
arm64 support for secretgen-controller

### ISSUE THREAD

**Issue by DanielePalaia** [carvel-dev/secretgen-controller#359]
Hello,

I'm an engineer from the RabbitMQ team. Our commercial operator is using the carvel toolchain and the tanzu-cluster-essential components (kapp and secret-gen controller) as prerequisite.

We are trying to produce a commercial arm64 image to solve a limitation on tanzu-net not supporting multi-arch image.

I can see that the tanzu-cluster-essential at the moment don't support multi-arch images commercially (probably for the same limitation on tanzunet registry).

What about the open source versions? I can see that I can install kapp on arm64
 kapp deploy -a kc -f https://github.com/vmware-tanzu/carvel-kapp-controller/releases/latest/download/release.yml

but not secretgen controller:
kapp deploy -a sg -f https://github.com/carvel-dev/secretgen-controller/releases/latest/download/release.yml

where it seems is using the amd64 image.

Is there a way we can install secret-gen controller on arm64?

Thank you!

**Comment by DanielePalaia** [comment]
This is the issue I'm having installing:

dpalaia@dpalaiaYMD6R bin % kapp deploy -a sg -f https://github.com/carvel-dev/secretgen-controller/releases/latest/download/release.yml
Target cluster 'https://35.193.186.83' (nodes: gke-daniele-test-default-pool-753b9d9b-0dt4, 2+)

2:20:23PM:  L ok: waiting on replicaset/secretgen-controller-5f69ff8c7f (apps/v1) namespace: secretgen-controller
2:20:23PM:  L ongoing: waiting on pod/secretgen-controller-5f69ff8c7f-g95st (v1) namespace: secretgen-controller
2:20:23PM:     ^ Condition Ready is not True (False)

dpalaia@dpalaiaYMD6R bin % kubectl logs secretgen-controller-5f69ff8c7f-g95st -n secretgen-controller
exec /secretgen-controller: exec format error

**Comment by praveenrewar** [comment]
Thanks @DanielePalaia for creating the issue. The problem seems to be in the Dockerfile, the arch is getting ignored because of a typo [here](https://github.com/carvel-dev/secretgen-controller/blob/cb3b86ddfb1a5341cd47861e81e9101708afe699/Dockerfile#L8).
It should be `GOARCH` instead of `GOSARCH`.

**Comment by DanielePalaia** [comment]
Ok thank you @praveenrewar to have investigated into it. When can we expect a new release?

**Comment by praveenrewar** [comment]
Hey @DanielePalaia! The current plan is to make a release in the first week of June. Does that work for you?

**Comment by DanielePalaia** [comment]
Sure @praveenrewar it is fine! Many thanks for your fix!
