### ISSUE TITLE
Consider a slimmer base image (e.g. distroless)

### ISSUE THREAD

**Issue by aaronshurley** [carvel-dev/secretgen-controller#40]
**Describe the problem/challenge you have**
We'd like to ship secretgen-controller with the minimum necessary bits. We're currently using [photon as our base image](https://github.com/vmware-tanzu/carvel-secretgen-controller/blob/develop/Dockerfile#L1). Is there a better (i.e. slimmer) option?

**Describe the solution you'd like**
Investigate alternative options (such as [distroless](https://github.com/GoogleContainerTools/distroless)) and determine if we should consider making a switch. If the changes appear to be simple, feel free to make the necessary changes.

**Anything else you would like to add:**
- similar issue in kapp-controller: vmware-tanzu/carvel-kapp-controller#419

**Comment by joe-kimmel-vmw** [comment]
in discussion w/ Mamta Upadhyay (vmware OSS-AIDE) it sounds like internal builds might not support distroless in the immediate future.

**Comment by aaronshurley** [comment]
After some discussion, we're deciding to hold off on investigating further into this issue until we learn more about other build processes that we may be able to leverage. If anyone from the community is interested in this work, please let us know.

**Comment by cppforlife** [comment]
switched to using scratch: https://github.com/vmware-tanzu/carvel-secretgen-controller/commit/e7ccd31525b51393f63412ecd6009984d5ebc99f
