### ISSUE TITLE
kubectl apply -f <secretgen-url> fails if the namespace is not created before hand.  

### ISSUE THREAD

**Issue by kvmw** [carvel-dev/secretgen-controller#55]
**What steps did you take:**
Just trying to install secretgetn-controller, using kubectl:
>  kubectl apply -f https://github.com/vmware-tanzu/carvel-secretgen-controller/releases/latest/download/release.yml

**What happened:**
the command finished with an error : 
> namespaces "secretgen-controller" not found

Eventually, the namespace  is created but without any resources ( no deployment, pods and ..)
```
customresourcedefinition.apiextensions.k8s.io/secretexports.secretgen.carvel.dev created
customresourcedefinition.apiextensions.k8s.io/secretimports.secretgen.carvel.dev created
customresourcedefinition.apiextensions.k8s.io/certificates.secretgen.k14s.io created
customresourcedefinition.apiextensions.k8s.io/passwords.secretgen.k14s.io created
customresourcedefinition.apiextensions.k8s.io/rsakeys.secretgen.k14s.io created
customresourcedefinition.apiextensions.k8s.io/sshkeys.secretgen.k14s.io created
namespace/secretgen-controller created
serviceaccount/secretgen-controller-sa created
clusterrole.rbac.authorization.k8s.io/secretgen-controller-cluster-role created
clusterrolebinding.rbac.authorization.k8s.io/secretgen-controller-cluster-role-binding created
Error from server (NotFound): error when creating "https://github.com/vmware-tanzu/carvel-secretgen-controller/releases/latest/download/release.yml": namespaces "secretgen-controller" not found
```

**What did you expect:**
create the namespace if it does not exist, before trying to install the resources there. 

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by rguske** [comment]
I just wanted to open the same issue 👍🏻

**Comment by cppforlife** [comment]
filed: https://github.com/vmware-tanzu/carvel-secretgen-controller/pull/62

**Comment by joe-kimmel-vmw** [comment]
fix will go out in the next release - thanks @kvmw and @rguske for reporting!
