### ISSUE TITLE
Create arm64 image for secretgen-controller

### ISSUE THREAD

**Issue by jorgemoralespou** [carvel-dev/secretgen-controller#57]
**Describe the problem/challenge you have**
Currently, secretgen-controller cannot run on an ARM64 host, as there is no image[0].

Could we switch to doing multi-arch builds and produce arm64 alongside amd64?

Related issue for kapp-controller: https://github.com/vmware-tanzu/carvel-kapp-controller/issues/573

This is needed for Tanzu Community Edition

**Comment by joe-kimmel-vmw** [comment]
Thanks @jorgemoralespou - is there a timetable for this ask?

**Comment by jorgemoralespou** [comment]
This is related to a bigger epic in tanzu community edition. Currently engineering have built their own image, so the sooner, the better, as with kapp-controller.
