### ISSUE TITLE
Add github documentation for the new SecretTemplate API.

### ISSUE THREAD

**Issue by gmrodgers** [carvel-dev/secretgen-controller#79]
Hey! As part of https://github.com/vmware-tanzu/carvel-secretgen-controller/pull/66 the SecretTemplate API was introduced but we held off then on adding documentation.  This was partially due to the possible confusion of the already existing SecretTemplate (part of password) that is already under [docs/](https://github.com/vmware-tanzu/carvel-secretgen-controller/tree/develop/docs).  As folks are started to use the API, it would be great to get some thorough docs and use cases in there and find a way for them to coexist with the previous secret template.

**Comment by gmrodgers** [comment]
@cppforlife I dont mind having a go at this and PRing in something to work on if that works for you? Or did yous already have something in mind?

**Comment by cppforlife** [comment]
@gmrodgers please go ahead, much needed addition.
