### ISSUE TITLE
Ensure secretgen-controller functionality is tested

### ISSUE THREAD

**Issue by aaronshurley** [carvel-dev/secretgen-controller#8]
**Describe the problem/challenge you have**
Since we're planning to invest further into secretgen-controller, we want to ensure that we're starting at a good place from a testing perspective.

**Describe the solution you'd like**
We want to use this story to determine if there are any substantial gaps in testing. If gaps are detected, then we'll fill them. If it's determined that there are many gaps then we can reconvene to determine the appropriate next steps.

**Anything else you would like to add:**
We could also consider using this time to bring the repo's practices up to date (such as issue templates, github actions, dependabot, etc.).

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by cppforlife** [comment]
v0.4.0/v0.5.0 are in a pretty good state.
