### ISSUE TITLE
Make sure secretgen-controller is production ready

### ISSUE THREAD

**Issue by ewrenn8** [carvel-dev/secretgen-controller#9]
Make sure sercetgen-controller is production ready. This is currently undefined, but a few suggestions are:

- [x] Using same linters as kapp-controller
- [x] Has automated testing
- [x] Sufficient logging
- [x] capture some knowledge in godocs
- [x] update to go 1.16. (currently 1.13)
- [x] debugability
- [x] fix up WarmUp
- [x] rename api group?
- [x] bump kapp-controller to use 0.5.0
- [x] check reconciliation delay (for when kc creates placeholder secret)
- [x] kapp will continiously reconcile out secretgen changes to image pull secrets -> fix in kapp, bump in kc
- [x] the automated tests cover examples folder

Also, look in to other kubernetes controller best practices to ensure we follow them (time box: half a day)

Additional deliverable: A set of detailed requirements needed to deem a new controller production ready. These should be applicable generically so we can easily create/adopt new controllers using defined practices.

**Comment by aaronshurley** [comment]
@cppforlife is going to look into logging

**Comment by joe-kimmel-vmw** [comment]
closing bc the last checkbox is checked
